---
# Copyright 2015, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Copy in sample dhcpd.conf file
  copy:
    src: "dhcpd.conf"
    dest: "/etc/dhcp/"
  when: ironic_standalone
  notify:
    - Restart isc-dhcp-server

- name: Create /tftpboot
  file:
    path: "/tftpboot"
    state: directory
    owner: "{{ ironic_system_user_name }}"
    group: "{{ ironic_system_group_name }}"
    mode: "0755"

- name: Copy in tftpd-hpa config file
  template:
    src: "tftpd-hpa.j2"
    dest: "/etc/default/tftpd-hpa"
  notify:
    - Restart tftpd-hpa

- name: Copy in tftpd-hpa map file
  copy:
    src: "map-file"
    dest: "/tftpboot/map-file"
  notify:
    - Restart tftpd-hpa

- name: Copy library modules into /tftpboot
  copy:
    src: "{{ item }}"
    dest: "/tftpboot/"
    remote_src: True
  with_items: "{{ ironic_library_modules_paths }}"

- name: Create "{{ ironic_httpboot_image_dir }}"
  file:
    path: "{{ ironic_httpboot_image_dir }}"
    state: directory
    owner: "{{ ironic_system_user_name }}"
    group: "{{ ironic_system_group_name }}"
    mode: "0755"
  when: ironic_httpboot_enabled

- name: Copy library modules into "{{ ironic_httpboot_image_dir }}"
  copy:
    src: "{{ item }}"
    dest: "{{ ironic_httpboot_image_dir }}"
    remote_src: True
  with_items: "{{ ironic_httpboot_library_modules_paths }}"
  when: ironic_httpboot_enabled

- name: Create empty index.html
  copy:
    content: |
      <!DOCTYPE html><title> </title>
    dest: "{{ ironic_httpboot_image_dir }}/index.html"
  when: ironic_httpboot_enabled
